#!/bin/sh

# chkconfig:    345 18 90
# description:  maxqworkerd - The MaxQ worker daemon startup script
#

# Source function library.
. /etc/rc.d/init.d/functions

[ -r /etc/sysconfig/maxq ] && . /etc/sysconfig/maxq
[ -z "$MAXQ_WORKER" ] && echo "/etc/sysconfig/maxq couldn't be sourced" && exit 1
PID="/var/run/maxq-worker.pid"
start() 
{
	[ -z "$MAXQ_WORKER_ARGS" ] && exit 0
        echo -n $"Starting maxq-worker: "
        eval sudo -u maxq -i $MAXQ_WORKER_START_SCRIPT 
	echo `cat /tmp/maxq-worker.pid` > $PID	
	touch /var/lock/subsys/maxqworkerd > /dev/null 2>&1
        echo
}

stop() 
{
        echo -n $"Shutting down maxq-worker: "
	eval "$MAXQ_CONTROLLER $MAXQ_CONTROLLER_STOP_WORKER_ARGS"
	rm -f  /var/lock/subsys/maxqworkerd > /dev/null 2>&1
        success	
        echo
}

[ -f  $MAXQ_WORKER_JAR ] || exit 0

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  status)
        ps -p `cat /var/run/maxq-worker.pid`  >> /dev/null
        RETVAL=$?
        ;;

  restart|reload)
	stop
	start
	;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 1
esac

exit ${RETVAL}
